project_name: rsearch

before:
  hooks:
    - go mod tidy

env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version=v{{.Version}}
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - '^merge:'
      - '^docs:'
      - '^test:'
